apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-devsecops
spec:
  replicas: 3
  selector:
    matchLabels:
      app: springboot-devsecops
  template:
    metadata:
      labels:
        app: springboot-devsecops
    spec:
      containers:
      - name: springboot-devsecops
        image: atharvs/springboot-devsecops:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
